sudo: required
services:
  - docker

before_install:
  - docker build -t pgsoncada/vite-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pgsoncada/vite-test npm test

after_success:
  - docker build -t pgsoncada/practice-client ./client
  - docker build -t pgsoncada/practice-nginx ./nginx
  - docker build -t pgsoncada/practice-server ./server

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push pgsoncada/practice-client
  - docker push pgsoncada/practice-nginx
  - docker push pgsoncada/practice-server