version: '3'
services:
  client:
    image: 'pgsoncada/practice-client'
    mem_limit: 128m
    hostname: client
    
  server:
    image: 'pgsoncada/practice-server'
    mem_limit: 128m
    hostname: api
    environment:
      - MYSQLUSER=$MYSQLUSER
      - MYSQLHOST=$MYSQLHOST
      - MYSQLDATABASE=$MYSQLDATABASE
      - MYSQLPASSWORD=$MYSQLPASSWORD
      - MYSQLPORT=$MYSQLPORT

  nginx:
    image: 'pgsoncada/practice-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '4000:80'